// Mocks generated by Mockito 5.4.6 from annotations
// in onebosssamuraibattle/test/boss_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;
import 'dart:ui' as _i9;

import 'package:flame/cache.dart' as _i10;
import 'package:flame/collisions.dart' as _i15;
import 'package:flame/components.dart' as _i2;
import 'package:flame/game.dart' as _i6;
import 'package:flame/sprite.dart' as _i24;
import 'package:flame/src/components/core/component_tree_root.dart' as _i19;
import 'package:flame/src/components/core/recycled_queue.dart' as _i7;
import 'package:flame/src/game/game_render_box.dart' as _i12;
import 'package:flame/src/game/game_widget/gesture_detector_builder.dart'
    as _i11;
import 'package:flame/src/game/overlay_manager.dart' as _i14;
import 'package:flame/src/rendering/decorator.dart' as _i18;
import 'package:flame_audio/flame_audio.dart' as _i17;
import 'package:flutter/gestures.dart' as _i22;
import 'package:flutter/material.dart' as _i13;
import 'package:flutter/rendering.dart' as _i23;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i21;
import 'package:onebosssamuraibattle/boss.dart' as _i5;
import 'package:onebosssamuraibattle/my_game.dart' as _i3;
import 'package:onebosssamuraibattle/player.dart' as _i4;
import 'package:ordered_set/ordered_set.dart' as _i16;
import 'package:ordered_set/read_only_ordered_set.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeJoystickComponent_0 extends _i1.SmartFake
    implements _i2.JoystickComponent {
  _FakeJoystickComponent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoystickDragHandle_1 extends _i1.SmartFake
    implements _i3.JoystickDragHandle {
  _FakeJoystickDragHandle_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayer_2 extends _i1.SmartFake implements _i4.Player {
  _FakePlayer_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBoss_3 extends _i1.SmartFake implements _i5.Boss {
  _FakeBoss_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWorld_4 extends _i1.SmartFake implements _i2.World {
  _FakeWorld_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCameraComponent_5 extends _i1.SmartFake
    implements _i2.CameraComponent {
  _FakeCameraComponent_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVector2_6 extends _i1.SmartFake implements _i6.Vector2 {
  _FakeVector2_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecycledQueue_7<T extends _i7.Disposable> extends _i1.SmartFake
    implements _i7.RecycledQueue<T> {
  _FakeRecycledQueue_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReadOnlyOrderedSet_8<E> extends _i1.SmartFake
    implements _i8.ReadOnlyOrderedSet<E> {
  _FakeReadOnlyOrderedSet_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeColor_9 extends _i1.SmartFake implements _i9.Color {
  _FakeColor_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextPaint_10 extends _i1.SmartFake implements _i6.TextPaint {
  _FakeTextPaint_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeImages_11 extends _i1.SmartFake implements _i10.Images {
  _FakeImages_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAssetsCache_12 extends _i1.SmartFake implements _i10.AssetsCache {
  _FakeAssetsCache_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGestureDetectorBuilder_13 extends _i1.SmartFake
    implements _i11.GestureDetectorBuilder {
  _FakeGestureDetectorBuilder_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameRenderBox_14 extends _i1.SmartFake
    implements _i12.GameRenderBox {
  _FakeGameRenderBox_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i13.DiagnosticLevel? minLevel = _i13.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeOverlayManager_15 extends _i1.SmartFake
    implements _i14.OverlayManager {
  _FakeOverlayManager_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMouseCursor_16 extends _i1.SmartFake implements _i13.MouseCursor {
  _FakeMouseCursor_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({
    _i13.DiagnosticLevel? minLevel = _i13.DiagnosticLevel.info,
  }) => super.toString();
}

class _FakeCollisionDetection_17<
  T extends _i15.Hitbox<T>,
  B extends _i15.Broadphase<T>
>
    extends _i1.SmartFake
    implements _i15.CollisionDetection<T, B> {
  _FakeCollisionDetection_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComponentsNotifier_18<T1 extends _i2.Component> extends _i1.SmartFake
    implements _i2.ComponentsNotifier<T1> {
  _FakeComponentsNotifier_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrderedSet_19<E> extends _i1.SmartFake
    implements _i16.OrderedSet<E> {
  _FakeOrderedSet_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSprite_20 extends _i1.SmartFake implements _i2.Sprite {
  _FakeSprite_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpriteAnimation_21 extends _i1.SmartFake
    implements _i2.SpriteAnimation {
  _FakeSpriteAnimation_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioPool_22 extends _i1.SmartFake implements _i17.AudioPool {
  _FakeAudioPool_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransform2D_23 extends _i1.SmartFake implements _i6.Transform2D {
  _FakeTransform2D_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDecorator_24 extends _i1.SmartFake implements _i18.Decorator {
  _FakeDecorator_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMatrix4_25 extends _i1.SmartFake implements _i6.Matrix4 {
  _FakeMatrix4_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotifyingVector2_26 extends _i1.SmartFake
    implements _i6.NotifyingVector2 {
  _FakeNotifyingVector2_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnchor_27 extends _i1.SmartFake implements _i2.Anchor {
  _FakeAnchor_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMyPixelGame_28 extends _i1.SmartFake implements _i3.MyPixelGame {
  _FakeMyPixelGame_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRect_29 extends _i1.SmartFake implements _i9.Rect {
  _FakeRect_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MyPixelGame].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyPixelGame extends _i1.Mock implements _i3.MyPixelGame {
  @override
  _i2.JoystickComponent get joystick =>
      (super.noSuchMethod(
            Invocation.getter(#joystick),
            returnValue: _FakeJoystickComponent_0(
              this,
              Invocation.getter(#joystick),
            ),
            returnValueForMissingStub: _FakeJoystickComponent_0(
              this,
              Invocation.getter(#joystick),
            ),
          )
          as _i2.JoystickComponent);

  @override
  _i3.JoystickDragHandle get joystickHandle =>
      (super.noSuchMethod(
            Invocation.getter(#joystickHandle),
            returnValue: _FakeJoystickDragHandle_1(
              this,
              Invocation.getter(#joystickHandle),
            ),
            returnValueForMissingStub: _FakeJoystickDragHandle_1(
              this,
              Invocation.getter(#joystickHandle),
            ),
          )
          as _i3.JoystickDragHandle);

  @override
  _i4.Player get player =>
      (super.noSuchMethod(
            Invocation.getter(#player),
            returnValue: _FakePlayer_2(this, Invocation.getter(#player)),
            returnValueForMissingStub: _FakePlayer_2(
              this,
              Invocation.getter(#player),
            ),
          )
          as _i4.Player);

  @override
  _i5.Boss get boss =>
      (super.noSuchMethod(
            Invocation.getter(#boss),
            returnValue: _FakeBoss_3(this, Invocation.getter(#boss)),
            returnValueForMissingStub: _FakeBoss_3(
              this,
              Invocation.getter(#boss),
            ),
          )
          as _i5.Boss);

  @override
  bool get startInRemapMode =>
      (super.noSuchMethod(
            Invocation.getter(#startInRemapMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get sunClickCount =>
      (super.noSuchMethod(
            Invocation.getter(#sunClickCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get cheatUnlocked =>
      (super.noSuchMethod(
            Invocation.getter(#cheatUnlocked),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get bossDamageDisabled =>
      (super.noSuchMethod(
            Invocation.getter(#bossDamageDisabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isEditingHUD =>
      (super.noSuchMethod(
            Invocation.getter(#isEditingHUD),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set joystick(_i2.JoystickComponent? value) => super.noSuchMethod(
    Invocation.setter(#joystick, value),
    returnValueForMissingStub: null,
  );

  @override
  set joystickHandle(_i3.JoystickDragHandle? value) => super.noSuchMethod(
    Invocation.setter(#joystickHandle, value),
    returnValueForMissingStub: null,
  );

  @override
  set player(_i4.Player? value) => super.noSuchMethod(
    Invocation.setter(#player, value),
    returnValueForMissingStub: null,
  );

  @override
  set boss(_i5.Boss? value) => super.noSuchMethod(
    Invocation.setter(#boss, value),
    returnValueForMissingStub: null,
  );

  @override
  set sunClickCount(int? value) => super.noSuchMethod(
    Invocation.setter(#sunClickCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set cheatUnlocked(bool? value) => super.noSuchMethod(
    Invocation.setter(#cheatUnlocked, value),
    returnValueForMissingStub: null,
  );

  @override
  set bossDamageDisabled(bool? value) => super.noSuchMethod(
    Invocation.setter(#bossDamageDisabled, value),
    returnValueForMissingStub: null,
  );

  @override
  set isEditingHUD(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEditingHUD, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.World get world =>
      (super.noSuchMethod(
            Invocation.getter(#world),
            returnValue: _FakeWorld_4(this, Invocation.getter(#world)),
            returnValueForMissingStub: _FakeWorld_4(
              this,
              Invocation.getter(#world),
            ),
          )
          as _i2.World);

  @override
  _i2.CameraComponent get camera =>
      (super.noSuchMethod(
            Invocation.getter(#camera),
            returnValue: _FakeCameraComponent_5(
              this,
              Invocation.getter(#camera),
            ),
            returnValueForMissingStub: _FakeCameraComponent_5(
              this,
              Invocation.getter(#camera),
            ),
          )
          as _i2.CameraComponent);

  @override
  List<_i2.ComponentsNotifier<_i2.Component>> get notifiers =>
      (super.noSuchMethod(
            Invocation.getter(#notifiers),
            returnValue: <_i2.ComponentsNotifier<_i2.Component>>[],
            returnValueForMissingStub:
                <_i2.ComponentsNotifier<_i2.Component>>[],
          )
          as List<_i2.ComponentsNotifier<_i2.Component>>);

  @override
  _i6.Vector2 get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: _FakeVector2_6(this, Invocation.getter(#size)),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#size),
            ),
          )
          as _i6.Vector2);

  @override
  bool get pauseWhenBackgrounded =>
      (super.noSuchMethod(
            Invocation.getter(#pauseWhenBackgrounded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isPausedOnBackground =>
      (super.noSuchMethod(
            Invocation.getter(#isPausedOnBackground),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set world(_i2.World? newWorld) => super.noSuchMethod(
    Invocation.setter(#world, newWorld),
    returnValueForMissingStub: null,
  );

  @override
  set camera(_i2.CameraComponent? newCameraComponent) => super.noSuchMethod(
    Invocation.setter(#camera, newCameraComponent),
    returnValueForMissingStub: null,
  );

  @override
  set pauseWhenBackgrounded(bool? value) => super.noSuchMethod(
    Invocation.setter(#pauseWhenBackgrounded, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.RecycledQueue<_i19.LifecycleEvent> get queue =>
      (super.noSuchMethod(
            Invocation.getter(#queue),
            returnValue: _FakeRecycledQueue_7<_i19.LifecycleEvent>(
              this,
              Invocation.getter(#queue),
            ),
            returnValueForMissingStub:
                _FakeRecycledQueue_7<_i19.LifecycleEvent>(
                  this,
                  Invocation.getter(#queue),
                ),
          )
          as _i7.RecycledQueue<_i19.LifecycleEvent>);

  @override
  bool get hasLifecycleEvents =>
      (super.noSuchMethod(
            Invocation.getter(#hasLifecycleEvents),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i20.Future<void> get lifecycleEventsProcessed =>
      (super.noSuchMethod(
            Invocation.getter(#lifecycleEventsProcessed),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#isLoaded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMounting =>
      (super.noSuchMethod(
            Invocation.getter(#isMounting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMounted =>
      (super.noSuchMethod(
            Invocation.getter(#isMounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRemoving =>
      (super.noSuchMethod(
            Invocation.getter(#isRemoving),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRemoved =>
      (super.noSuchMethod(
            Invocation.getter(#isRemoved),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i20.Future<void> get loaded =>
      (super.noSuchMethod(
            Invocation.getter(#loaded),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> get removed =>
      (super.noSuchMethod(
            Invocation.getter(#removed),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i8.ReadOnlyOrderedSet<_i2.Component> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: _FakeReadOnlyOrderedSet_8<_i2.Component>(
              this,
              Invocation.getter(#children),
            ),
            returnValueForMissingStub: _FakeReadOnlyOrderedSet_8<_i2.Component>(
              this,
              Invocation.getter(#children),
            ),
          )
          as _i8.ReadOnlyOrderedSet<_i2.Component>);

  @override
  bool get hasChildren =>
      (super.noSuchMethod(
            Invocation.getter(#hasChildren),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get priority =>
      (super.noSuchMethod(
            Invocation.getter(#priority),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get debugMode =>
      (super.noSuchMethod(
            Invocation.getter(#debugMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Color get debugColor =>
      (super.noSuchMethod(
            Invocation.getter(#debugColor),
            returnValue: _FakeColor_9(this, Invocation.getter(#debugColor)),
            returnValueForMissingStub: _FakeColor_9(
              this,
              Invocation.getter(#debugColor),
            ),
          )
          as _i9.Color);

  @override
  _i9.Paint get debugPaint =>
      (super.noSuchMethod(
            Invocation.getter(#debugPaint),
            returnValue: _i21.dummyValue<_i9.Paint>(
              this,
              Invocation.getter(#debugPaint),
            ),
            returnValueForMissingStub: _i21.dummyValue<_i9.Paint>(
              this,
              Invocation.getter(#debugPaint),
            ),
          )
          as _i9.Paint);

  @override
  _i6.TextPaint get debugTextPaint =>
      (super.noSuchMethod(
            Invocation.getter(#debugTextPaint),
            returnValue: _FakeTextPaint_10(
              this,
              Invocation.getter(#debugTextPaint),
            ),
            returnValueForMissingStub: _FakeTextPaint_10(
              this,
              Invocation.getter(#debugTextPaint),
            ),
          )
          as _i6.TextPaint);

  @override
  set parent(_i2.Component? newParent) => super.noSuchMethod(
    Invocation.setter(#parent, newParent),
    returnValueForMissingStub: null,
  );

  @override
  set priority(int? newPriority) => super.noSuchMethod(
    Invocation.setter(#priority, newPriority),
    returnValueForMissingStub: null,
  );

  @override
  set debugMode(bool? value) => super.noSuchMethod(
    Invocation.setter(#debugMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set debugCoordinatesPrecision(int? value) => super.noSuchMethod(
    Invocation.setter(#debugCoordinatesPrecision, value),
    returnValueForMissingStub: null,
  );

  @override
  set debugColor(_i9.Color? value) => super.noSuchMethod(
    Invocation.setter(#debugColor, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Images get images =>
      (super.noSuchMethod(
            Invocation.getter(#images),
            returnValue: _FakeImages_11(this, Invocation.getter(#images)),
            returnValueForMissingStub: _FakeImages_11(
              this,
              Invocation.getter(#images),
            ),
          )
          as _i10.Images);

  @override
  _i10.AssetsCache get assets =>
      (super.noSuchMethod(
            Invocation.getter(#assets),
            returnValue: _FakeAssetsCache_12(this, Invocation.getter(#assets)),
            returnValueForMissingStub: _FakeAssetsCache_12(
              this,
              Invocation.getter(#assets),
            ),
          )
          as _i10.AssetsCache);

  @override
  _i11.GestureDetectorBuilder get gestureDetectors =>
      (super.noSuchMethod(
            Invocation.getter(#gestureDetectors),
            returnValue: _FakeGestureDetectorBuilder_13(
              this,
              Invocation.getter(#gestureDetectors),
            ),
            returnValueForMissingStub: _FakeGestureDetectorBuilder_13(
              this,
              Invocation.getter(#gestureDetectors),
            ),
          )
          as _i11.GestureDetectorBuilder);

  @override
  _i12.GameRenderBox get renderBox =>
      (super.noSuchMethod(
            Invocation.getter(#renderBox),
            returnValue: _FakeGameRenderBox_14(
              this,
              Invocation.getter(#renderBox),
            ),
            returnValueForMissingStub: _FakeGameRenderBox_14(
              this,
              Invocation.getter(#renderBox),
            ),
          )
          as _i12.GameRenderBox);

  @override
  bool get isAttached =>
      (super.noSuchMethod(
            Invocation.getter(#isAttached),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Vector2 get canvasSize =>
      (super.noSuchMethod(
            Invocation.getter(#canvasSize),
            returnValue: _FakeVector2_6(this, Invocation.getter(#canvasSize)),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#canvasSize),
            ),
          )
          as _i6.Vector2);

  @override
  bool get hasLayout =>
      (super.noSuchMethod(
            Invocation.getter(#hasLayout),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get paused =>
      (super.noSuchMethod(
            Invocation.getter(#paused),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i14.OverlayManager get overlays =>
      (super.noSuchMethod(
            Invocation.getter(#overlays),
            returnValue: _FakeOverlayManager_15(
              this,
              Invocation.getter(#overlays),
            ),
            returnValueForMissingStub: _FakeOverlayManager_15(
              this,
              Invocation.getter(#overlays),
            ),
          )
          as _i14.OverlayManager);

  @override
  _i13.MouseCursor get mouseCursor =>
      (super.noSuchMethod(
            Invocation.getter(#mouseCursor),
            returnValue: _FakeMouseCursor_16(
              this,
              Invocation.getter(#mouseCursor),
            ),
            returnValueForMissingStub: _FakeMouseCursor_16(
              this,
              Invocation.getter(#mouseCursor),
            ),
          )
          as _i13.MouseCursor);

  @override
  List<_i9.VoidCallback> get gameStateListeners =>
      (super.noSuchMethod(
            Invocation.getter(#gameStateListeners),
            returnValue: <_i9.VoidCallback>[],
            returnValueForMissingStub: <_i9.VoidCallback>[],
          )
          as List<_i9.VoidCallback>);

  @override
  set images(_i10.Images? value) => super.noSuchMethod(
    Invocation.setter(#images, value),
    returnValueForMissingStub: null,
  );

  @override
  set assets(_i10.AssetsCache? value) => super.noSuchMethod(
    Invocation.setter(#assets, value),
    returnValueForMissingStub: null,
  );

  @override
  set mouseDetector(void Function(_i22.PointerHoverEvent)? newMouseDetector) =>
      super.noSuchMethod(
        Invocation.setter(#mouseDetector, newMouseDetector),
        returnValueForMissingStub: null,
      );

  @override
  set paused(bool? value) => super.noSuchMethod(
    Invocation.setter(#paused, value),
    returnValueForMissingStub: null,
  );

  @override
  set mouseCursor(_i13.MouseCursor? value) => super.noSuchMethod(
    Invocation.setter(#mouseCursor, value),
    returnValueForMissingStub: null,
  );

  @override
  _i15.CollisionDetection<_i15.ShapeHitbox, _i15.Broadphase<_i15.ShapeHitbox>>
  get collisionDetection =>
      (super.noSuchMethod(
            Invocation.getter(#collisionDetection),
            returnValue:
                _FakeCollisionDetection_17<
                  _i15.ShapeHitbox,
                  _i15.Broadphase<_i15.ShapeHitbox>
                >(this, Invocation.getter(#collisionDetection)),
            returnValueForMissingStub:
                _FakeCollisionDetection_17<
                  _i15.ShapeHitbox,
                  _i15.Broadphase<_i15.ShapeHitbox>
                >(this, Invocation.getter(#collisionDetection)),
          )
          as _i15.CollisionDetection<
            _i15.ShapeHitbox,
            _i15.Broadphase<_i15.ShapeHitbox>
          >);

  @override
  set collisionDetection(
    _i15.CollisionDetection<
      _i15.ShapeHitbox,
      _i15.Broadphase<_i15.ShapeHitbox>
    >?
    cd,
  ) => super.noSuchMethod(
    Invocation.setter(#collisionDetection, cd),
    returnValueForMissingStub: null,
  );

  @override
  _i20.Future<void> onLoad() =>
      (super.noSuchMethod(
            Invocation.method(#onLoad, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  void resetGame() => super.noSuchMethod(
    Invocation.method(#resetGame, []),
    returnValueForMissingStub: null,
  );

  @override
  void mount() => super.noSuchMethod(
    Invocation.method(#mount, []),
    returnValueForMissingStub: null,
  );

  @override
  void finalizeRemoval() => super.noSuchMethod(
    Invocation.method(#finalizeRemoval, []),
    returnValueForMissingStub: null,
  );

  @override
  void render(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#render, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  void renderTree(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#renderTree, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  void update(double? dt) => super.noSuchMethod(
    Invocation.method(#update, [dt]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTree(double? dt) => super.noSuchMethod(
    Invocation.method(#updateTree, [dt]),
    returnValueForMissingStub: null,
  );

  @override
  void onGameResize(_i6.Vector2? size) => super.noSuchMethod(
    Invocation.method(#onGameResize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  _i20.Future<void> ready() =>
      (super.noSuchMethod(
            Invocation.method(#ready, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  bool containsLocalPoint(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#containsLocalPoint, [point]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double currentTime() =>
      (super.noSuchMethod(
            Invocation.method(#currentTime, []),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i2.ComponentsNotifier<T> componentsNotifier<T extends _i2.Component>() =>
      (super.noSuchMethod(
            Invocation.method(#componentsNotifier, []),
            returnValue: _FakeComponentsNotifier_18<T>(
              this,
              Invocation.method(#componentsNotifier, []),
            ),
            returnValueForMissingStub: _FakeComponentsNotifier_18<T>(
              this,
              Invocation.method(#componentsNotifier, []),
            ),
          )
          as _i2.ComponentsNotifier<T>);

  @override
  void propagateToApplicableNotifiers(
    _i2.Component? component,
    void Function(_i2.ComponentsNotifier<_i2.Component>)? callback,
  ) => super.noSuchMethod(
    Invocation.method(#propagateToApplicableNotifiers, [component, callback]),
    returnValueForMissingStub: null,
  );

  @override
  void lifecycleStateChange(_i9.AppLifecycleState? state) => super.noSuchMethod(
    Invocation.method(#lifecycleStateChange, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void pauseEngine() => super.noSuchMethod(
    Invocation.method(#pauseEngine, []),
    returnValueForMissingStub: null,
  );

  @override
  void resumeEngine() => super.noSuchMethod(
    Invocation.method(#resumeEngine, []),
    returnValueForMissingStub: null,
  );

  @override
  void enqueueAdd(_i2.Component? child, _i2.Component? parent) =>
      super.noSuchMethod(
        Invocation.method(#enqueueAdd, [child, parent]),
        returnValueForMissingStub: null,
      );

  @override
  void dequeueAdd(_i2.Component? child, _i2.Component? parent) =>
      super.noSuchMethod(
        Invocation.method(#dequeueAdd, [child, parent]),
        returnValueForMissingStub: null,
      );

  @override
  void enqueueRemove(_i2.Component? child, _i2.Component? parent) =>
      super.noSuchMethod(
        Invocation.method(#enqueueRemove, [child, parent]),
        returnValueForMissingStub: null,
      );

  @override
  void dequeueRemove(_i2.Component? child) => super.noSuchMethod(
    Invocation.method(#dequeueRemove, [child]),
    returnValueForMissingStub: null,
  );

  @override
  void enqueueMove(_i2.Component? child, _i2.Component? newParent) =>
      super.noSuchMethod(
        Invocation.method(#enqueueMove, [child, newParent]),
        returnValueForMissingStub: null,
      );

  @override
  void enqueuePriorityChange(_i2.Component? parent, _i2.Component? child) =>
      super.noSuchMethod(
        Invocation.method(#enqueuePriorityChange, [parent, child]),
        returnValueForMissingStub: null,
      );

  @override
  void processLifecycleEvents() => super.noSuchMethod(
    Invocation.method(#processLifecycleEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  void handleResize(_i6.Vector2? size) => super.noSuchMethod(
    Invocation.method(#handleResize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  void registerKey(_i2.ComponentKey? key, _i2.Component? component) =>
      super.noSuchMethod(
        Invocation.method(#registerKey, [key, component]),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterKey(_i2.ComponentKey? key) => super.noSuchMethod(
    Invocation.method(#unregisterKey, [key]),
    returnValueForMissingStub: null,
  );

  @override
  T? findByKey<T extends _i2.Component>(_i2.ComponentKey? key) =>
      (super.noSuchMethod(
            Invocation.method(#findByKey, [key]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  T? findByKeyName<T extends _i2.Component>(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#findByKeyName, [name]),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  void rebalanceChildren() => super.noSuchMethod(
    Invocation.method(#rebalanceChildren, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.OrderedSet<_i2.Component> createComponentSet() =>
      (super.noSuchMethod(
            Invocation.method(#createComponentSet, []),
            returnValue: _FakeOrderedSet_19<_i2.Component>(
              this,
              Invocation.method(#createComponentSet, []),
            ),
            returnValueForMissingStub: _FakeOrderedSet_19<_i2.Component>(
              this,
              Invocation.method(#createComponentSet, []),
            ),
          )
          as _i16.OrderedSet<_i2.Component>);

  @override
  T? findParent<T extends _i2.Component>({bool? includeSelf = false}) =>
      (super.noSuchMethod(
            Invocation.method(#findParent, [], {#includeSelf: includeSelf}),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  Iterable<_i2.Component> ancestors({bool? includeSelf = false}) =>
      (super.noSuchMethod(
            Invocation.method(#ancestors, [], {#includeSelf: includeSelf}),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  Iterable<_i2.Component> descendants({
    bool? includeSelf = false,
    bool? reversed = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#descendants, [], {
              #includeSelf: includeSelf,
              #reversed: reversed,
            }),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  bool propagateToChildren<T extends _i2.Component>(
    bool Function(T)? handler, {
    bool? includeSelf = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #propagateToChildren,
              [handler],
              {#includeSelf: includeSelf},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool contains(_i2.Component? c) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [c]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onMount() => super.noSuchMethod(
    Invocation.method(#onMount, []),
    returnValueForMissingStub: null,
  );

  @override
  void onRemove() => super.noSuchMethod(
    Invocation.method(#onRemove, []),
    returnValueForMissingStub: null,
  );

  @override
  void onParentResize(_i6.Vector2? maxSize) => super.noSuchMethod(
    Invocation.method(#onParentResize, [maxSize]),
    returnValueForMissingStub: null,
  );

  @override
  void onChildrenChanged(_i2.Component? child, _i2.ChildrenChangeType? type) =>
      super.noSuchMethod(
        Invocation.method(#onChildrenChanged, [child, type]),
        returnValueForMissingStub: null,
      );

  @override
  _i20.FutureOr<void> add(_i2.Component? component) =>
      (super.noSuchMethod(
            Invocation.method(#add, [component]),
            returnValueForMissingStub: null,
          )
          as _i20.FutureOr<void>);

  @override
  _i20.FutureOr<void> addToParent(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#addToParent, [parent]),
            returnValueForMissingStub: null,
          )
          as _i20.FutureOr<void>);

  @override
  _i20.Future<void> addAll(Iterable<_i2.Component>? components) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [components]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  void remove(_i2.Component? component) => super.noSuchMethod(
    Invocation.method(#remove, [component]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFromParent() => super.noSuchMethod(
    Invocation.method(#removeFromParent, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeAll(Iterable<_i2.Component>? components) => super.noSuchMethod(
    Invocation.method(#removeAll, [components]),
    returnValueForMissingStub: null,
  );

  @override
  void removeWhere(bool Function(_i2.Component)? test) => super.noSuchMethod(
    Invocation.method(#removeWhere, [test]),
    returnValueForMissingStub: null,
  );

  @override
  bool containsPoint(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#containsPoint, [point]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  Iterable<_i2.Component> componentsAtPoint(
    _i6.Vector2? point, [
    List<_i6.Vector2>? nestedPoints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#componentsAtPoint, [point, nestedPoints]),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  Iterable<_i2.Component> componentsAtLocation<T>(
    T? locationContext,
    List<T>? nestedContexts,
    T? Function(_i2.CoordinateTransform, T)? transformContext,
    bool Function(_i2.Component, T)? checkContains,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#componentsAtLocation, [
              locationContext,
              nestedContexts,
              transformContext,
              checkContains,
            ]),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventAdd(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventAdd, [parent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventRemove(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventRemove, [parent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventMove(
    _i2.Component? newParent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventMove, [newParent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  void setLoaded() => super.noSuchMethod(
    Invocation.method(#setLoaded, []),
    returnValueForMissingStub: null,
  );

  @override
  void setMounted() => super.noSuchMethod(
    Invocation.method(#setMounted, []),
    returnValueForMissingStub: null,
  );

  @override
  void setRemoved() => super.noSuchMethod(
    Invocation.method(#setRemoved, []),
    returnValueForMissingStub: null,
  );

  @override
  void renderDebugMode(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#renderDebugMode, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Color backgroundColor() =>
      (super.noSuchMethod(
            Invocation.method(#backgroundColor, []),
            returnValue: _FakeColor_9(
              this,
              Invocation.method(#backgroundColor, []),
            ),
            returnValueForMissingStub: _FakeColor_9(
              this,
              Invocation.method(#backgroundColor, []),
            ),
          )
          as _i9.Color);

  @override
  void assertHasLayout() => super.noSuchMethod(
    Invocation.method(#assertHasLayout, []),
    returnValueForMissingStub: null,
  );

  @override
  void attach(_i23.PipelineOwner? owner, _i12.GameRenderBox? gameRenderBox) =>
      super.noSuchMethod(
        Invocation.method(#attach, [owner, gameRenderBox]),
        returnValueForMissingStub: null,
      );

  @override
  void onAttach() => super.noSuchMethod(
    Invocation.method(#onAttach, []),
    returnValueForMissingStub: null,
  );

  @override
  void detach() => super.noSuchMethod(
    Invocation.method(#detach, []),
    returnValueForMissingStub: null,
  );

  @override
  void onDispose() => super.noSuchMethod(
    Invocation.method(#onDispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void onDetach() => super.noSuchMethod(
    Invocation.method(#onDetach, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Vector2 convertGlobalToLocalCoordinate(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#convertGlobalToLocalCoordinate, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#convertGlobalToLocalCoordinate, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#convertGlobalToLocalCoordinate, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 convertLocalToGlobalCoordinate(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#convertLocalToGlobalCoordinate, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#convertLocalToGlobalCoordinate, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#convertLocalToGlobalCoordinate, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  _i20.Future<_i2.Sprite> loadSprite(
    String? path, {
    _i6.Vector2? srcSize,
    _i6.Vector2? srcPosition,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadSprite,
              [path],
              {#srcSize: srcSize, #srcPosition: srcPosition},
            ),
            returnValue: _i20.Future<_i2.Sprite>.value(
              _FakeSprite_20(
                this,
                Invocation.method(
                  #loadSprite,
                  [path],
                  {#srcSize: srcSize, #srcPosition: srcPosition},
                ),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i2.Sprite>.value(
              _FakeSprite_20(
                this,
                Invocation.method(
                  #loadSprite,
                  [path],
                  {#srcSize: srcSize, #srcPosition: srcPosition},
                ),
              ),
            ),
          )
          as _i20.Future<_i2.Sprite>);

  @override
  _i20.Future<_i2.SpriteAnimation> loadSpriteAnimation(
    String? path,
    _i2.SpriteAnimationData? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadSpriteAnimation, [path, data]),
            returnValue: _i20.Future<_i2.SpriteAnimation>.value(
              _FakeSpriteAnimation_21(
                this,
                Invocation.method(#loadSpriteAnimation, [path, data]),
              ),
            ),
            returnValueForMissingStub: _i20.Future<_i2.SpriteAnimation>.value(
              _FakeSpriteAnimation_21(
                this,
                Invocation.method(#loadSpriteAnimation, [path, data]),
              ),
            ),
          )
          as _i20.Future<_i2.SpriteAnimation>);

  @override
  void stepEngine({double? stepTime = 0.016666666666666666}) =>
      super.noSuchMethod(
        Invocation.method(#stepEngine, [], {#stepTime: stepTime}),
        returnValueForMissingStub: null,
      );

  @override
  void addGameStateListener(_i9.VoidCallback? callback) => super.noSuchMethod(
    Invocation.method(#addGameStateListener, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeGameStateListener(_i9.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeGameStateListener, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void refreshWidget({bool? isInternalRefresh = true}) => super.noSuchMethod(
    Invocation.method(#refreshWidget, [], {
      #isInternalRefresh: isInternalRefresh,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Player].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayer extends _i1.Mock implements _i4.Player {
  @override
  _i2.JoystickComponent get joystick =>
      (super.noSuchMethod(
            Invocation.getter(#joystick),
            returnValue: _FakeJoystickComponent_0(
              this,
              Invocation.getter(#joystick),
            ),
            returnValueForMissingStub: _FakeJoystickComponent_0(
              this,
              Invocation.getter(#joystick),
            ),
          )
          as _i2.JoystickComponent);

  @override
  bool get isInvincibleCheat =>
      (super.noSuchMethod(
            Invocation.getter(#isInvincibleCheat),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get damageMultiplier =>
      (super.noSuchMethod(
            Invocation.getter(#damageMultiplier),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get paralyzeTimer =>
      (super.noSuchMethod(
            Invocation.getter(#paralyzeTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isParalyzed =>
      (super.noSuchMethod(
            Invocation.getter(#isParalyzed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get arquivoPasso =>
      (super.noSuchMethod(
            Invocation.getter(#arquivoPasso),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#arquivoPasso),
            ),
            returnValueForMissingStub: _i21.dummyValue<String>(
              this,
              Invocation.getter(#arquivoPasso),
            ),
          )
          as String);

  @override
  String get arquivoPulo =>
      (super.noSuchMethod(
            Invocation.getter(#arquivoPulo),
            returnValue: _i21.dummyValue<String>(
              this,
              Invocation.getter(#arquivoPulo),
            ),
            returnValueForMissingStub: _i21.dummyValue<String>(
              this,
              Invocation.getter(#arquivoPulo),
            ),
          )
          as String);

  @override
  _i17.AudioPool get poolPulo =>
      (super.noSuchMethod(
            Invocation.getter(#poolPulo),
            returnValue: _FakeAudioPool_22(this, Invocation.getter(#poolPulo)),
            returnValueForMissingStub: _FakeAudioPool_22(
              this,
              Invocation.getter(#poolPulo),
            ),
          )
          as _i17.AudioPool);

  @override
  _i17.AudioPool get poolPasso =>
      (super.noSuchMethod(
            Invocation.getter(#poolPasso),
            returnValue: _FakeAudioPool_22(this, Invocation.getter(#poolPasso)),
            returnValueForMissingStub: _FakeAudioPool_22(
              this,
              Invocation.getter(#poolPasso),
            ),
          )
          as _i17.AudioPool);

  @override
  double get stepTimer =>
      (super.noSuchMethod(
            Invocation.getter(#stepTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get stepInterval =>
      (super.noSuchMethod(
            Invocation.getter(#stepInterval),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get speed =>
      (super.noSuchMethod(
            Invocation.getter(#speed),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i6.Vector2 get velocity =>
      (super.noSuchMethod(
            Invocation.getter(#velocity),
            returnValue: _FakeVector2_6(this, Invocation.getter(#velocity)),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#velocity),
            ),
          )
          as _i6.Vector2);

  @override
  double get groundLevelY =>
      (super.noSuchMethod(
            Invocation.getter(#groundLevelY),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int get jumpCount =>
      (super.noSuchMethod(
            Invocation.getter(#jumpCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get isInvincible =>
      (super.noSuchMethod(
            Invocation.getter(#isInvincible),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get gravity =>
      (super.noSuchMethod(
            Invocation.getter(#gravity),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isBlocking =>
      (super.noSuchMethod(
            Invocation.getter(#isBlocking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get blockTimer =>
      (super.noSuchMethod(
            Invocation.getter(#blockTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get parryWindow =>
      (super.noSuchMethod(
            Invocation.getter(#parryWindow),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get health =>
      (super.noSuchMethod(
            Invocation.getter(#health),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get specialMeter =>
      (super.noSuchMethod(
            Invocation.getter(#specialMeter),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int get comboMultiplier =>
      (super.noSuchMethod(
            Invocation.getter(#comboMultiplier),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get hitCount =>
      (super.noSuchMethod(
            Invocation.getter(#hitCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  double get continuousHitTimer =>
      (super.noSuchMethod(
            Invocation.getter(#continuousHitTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get timeSinceLastHit =>
      (super.noSuchMethod(
            Invocation.getter(#timeSinceLastHit),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get decayTimer =>
      (super.noSuchMethod(
            Invocation.getter(#decayTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isDashing =>
      (super.noSuchMethod(
            Invocation.getter(#isDashing),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  double get dashTimer =>
      (super.noSuchMethod(
            Invocation.getter(#dashTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get dashCooldownTimer =>
      (super.noSuchMethod(
            Invocation.getter(#dashCooldownTimer),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get tempoTotalDash =>
      (super.noSuchMethod(
            Invocation.getter(#tempoTotalDash),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get tempoDoImpulso =>
      (super.noSuchMethod(
            Invocation.getter(#tempoDoImpulso),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get tempoDeRecargaDash =>
      (super.noSuchMethod(
            Invocation.getter(#tempoDeRecargaDash),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool get isJumping =>
      (super.noSuchMethod(
            Invocation.getter(#isJumping),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFacingRight =>
      (super.noSuchMethod(
            Invocation.getter(#isFacingRight),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isWalking =>
      (super.noSuchMethod(
            Invocation.getter(#isWalking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAttacking =>
      (super.noSuchMethod(
            Invocation.getter(#isAttacking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get currentAttackStep =>
      (super.noSuchMethod(
            Invocation.getter(#currentAttackStep),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get comboTarget =>
      (super.noSuchMethod(
            Invocation.getter(#comboTarget),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get hasDealtDamageThisStep =>
      (super.noSuchMethod(
            Invocation.getter(#hasDealtDamageThisStep),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isParrySuccessAnim =>
      (super.noSuchMethod(
            Invocation.getter(#isParrySuccessAnim),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isParryFailAnim =>
      (super.noSuchMethod(
            Invocation.getter(#isParryFailAnim),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set boss(_i5.Boss? value) => super.noSuchMethod(
    Invocation.setter(#boss, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInvincibleCheat(bool? value) => super.noSuchMethod(
    Invocation.setter(#isInvincibleCheat, value),
    returnValueForMissingStub: null,
  );

  @override
  set damageMultiplier(double? value) => super.noSuchMethod(
    Invocation.setter(#damageMultiplier, value),
    returnValueForMissingStub: null,
  );

  @override
  set paralyzeTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#paralyzeTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set poolPulo(_i17.AudioPool? value) => super.noSuchMethod(
    Invocation.setter(#poolPulo, value),
    returnValueForMissingStub: null,
  );

  @override
  set poolPasso(_i17.AudioPool? value) => super.noSuchMethod(
    Invocation.setter(#poolPasso, value),
    returnValueForMissingStub: null,
  );

  @override
  set stepTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#stepTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set speed(double? value) => super.noSuchMethod(
    Invocation.setter(#speed, value),
    returnValueForMissingStub: null,
  );

  @override
  set velocity(_i6.Vector2? value) => super.noSuchMethod(
    Invocation.setter(#velocity, value),
    returnValueForMissingStub: null,
  );

  @override
  set jumpCount(int? value) => super.noSuchMethod(
    Invocation.setter(#jumpCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInvincible(bool? value) => super.noSuchMethod(
    Invocation.setter(#isInvincible, value),
    returnValueForMissingStub: null,
  );

  @override
  set gravity(double? value) => super.noSuchMethod(
    Invocation.setter(#gravity, value),
    returnValueForMissingStub: null,
  );

  @override
  set isBlocking(bool? value) => super.noSuchMethod(
    Invocation.setter(#isBlocking, value),
    returnValueForMissingStub: null,
  );

  @override
  set blockTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#blockTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set health(double? value) => super.noSuchMethod(
    Invocation.setter(#health, value),
    returnValueForMissingStub: null,
  );

  @override
  set specialMeter(double? value) => super.noSuchMethod(
    Invocation.setter(#specialMeter, value),
    returnValueForMissingStub: null,
  );

  @override
  set comboMultiplier(int? value) => super.noSuchMethod(
    Invocation.setter(#comboMultiplier, value),
    returnValueForMissingStub: null,
  );

  @override
  set hitCount(int? value) => super.noSuchMethod(
    Invocation.setter(#hitCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set continuousHitTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#continuousHitTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set timeSinceLastHit(double? value) => super.noSuchMethod(
    Invocation.setter(#timeSinceLastHit, value),
    returnValueForMissingStub: null,
  );

  @override
  set decayTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#decayTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set isDashing(bool? value) => super.noSuchMethod(
    Invocation.setter(#isDashing, value),
    returnValueForMissingStub: null,
  );

  @override
  set dashTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#dashTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set dashCooldownTimer(double? value) => super.noSuchMethod(
    Invocation.setter(#dashCooldownTimer, value),
    returnValueForMissingStub: null,
  );

  @override
  set isJumping(bool? value) => super.noSuchMethod(
    Invocation.setter(#isJumping, value),
    returnValueForMissingStub: null,
  );

  @override
  set isFacingRight(bool? value) => super.noSuchMethod(
    Invocation.setter(#isFacingRight, value),
    returnValueForMissingStub: null,
  );

  @override
  set isWalking(bool? value) => super.noSuchMethod(
    Invocation.setter(#isWalking, value),
    returnValueForMissingStub: null,
  );

  @override
  set isAttacking(bool? value) => super.noSuchMethod(
    Invocation.setter(#isAttacking, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentAttackStep(int? value) => super.noSuchMethod(
    Invocation.setter(#currentAttackStep, value),
    returnValueForMissingStub: null,
  );

  @override
  set comboTarget(int? value) => super.noSuchMethod(
    Invocation.setter(#comboTarget, value),
    returnValueForMissingStub: null,
  );

  @override
  set hasDealtDamageThisStep(bool? value) => super.noSuchMethod(
    Invocation.setter(#hasDealtDamageThisStep, value),
    returnValueForMissingStub: null,
  );

  @override
  set isParrySuccessAnim(bool? value) => super.noSuchMethod(
    Invocation.setter(#isParrySuccessAnim, value),
    returnValueForMissingStub: null,
  );

  @override
  set isParryFailAnim(bool? value) => super.noSuchMethod(
    Invocation.setter(#isParryFailAnim, value),
    returnValueForMissingStub: null,
  );

  @override
  set walkTicker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#walkTicker, value),
    returnValueForMissingStub: null,
  );

  @override
  set idleTicker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#idleTicker, value),
    returnValueForMissingStub: null,
  );

  @override
  set jumpTicker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#jumpTicker, value),
    returnValueForMissingStub: null,
  );

  @override
  set dashImpulseTicker(_i24.SpriteAnimationTicker? value) =>
      super.noSuchMethod(
        Invocation.setter(#dashImpulseTicker, value),
        returnValueForMissingStub: null,
      );

  @override
  set dashRunTicker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#dashRunTicker, value),
    returnValueForMissingStub: null,
  );

  @override
  set attack1Ticker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#attack1Ticker, value),
    returnValueForMissingStub: null,
  );

  @override
  set attack2Ticker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#attack2Ticker, value),
    returnValueForMissingStub: null,
  );

  @override
  set attack3Ticker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#attack3Ticker, value),
    returnValueForMissingStub: null,
  );

  @override
  set parrySuccessTicker(_i24.SpriteAnimationTicker? value) =>
      super.noSuchMethod(
        Invocation.setter(#parrySuccessTicker, value),
        returnValueForMissingStub: null,
      );

  @override
  set parryFailTicker(_i24.SpriteAnimationTicker? value) => super.noSuchMethod(
    Invocation.setter(#parryFailTicker, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Transform2D get transform =>
      (super.noSuchMethod(
            Invocation.getter(#transform),
            returnValue: _FakeTransform2D_23(
              this,
              Invocation.getter(#transform),
            ),
            returnValueForMissingStub: _FakeTransform2D_23(
              this,
              Invocation.getter(#transform),
            ),
          )
          as _i6.Transform2D);

  @override
  double get nativeAngle =>
      (super.noSuchMethod(
            Invocation.getter(#nativeAngle),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i18.Decorator get decorator =>
      (super.noSuchMethod(
            Invocation.getter(#decorator),
            returnValue: _FakeDecorator_24(this, Invocation.getter(#decorator)),
            returnValueForMissingStub: _FakeDecorator_24(
              this,
              Invocation.getter(#decorator),
            ),
          )
          as _i18.Decorator);

  @override
  _i6.Matrix4 get transformMatrix =>
      (super.noSuchMethod(
            Invocation.getter(#transformMatrix),
            returnValue: _FakeMatrix4_25(
              this,
              Invocation.getter(#transformMatrix),
            ),
            returnValueForMissingStub: _FakeMatrix4_25(
              this,
              Invocation.getter(#transformMatrix),
            ),
          )
          as _i6.Matrix4);

  @override
  _i6.NotifyingVector2 get position =>
      (super.noSuchMethod(
            Invocation.getter(#position),
            returnValue: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#position),
            ),
            returnValueForMissingStub: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#position),
            ),
          )
          as _i6.NotifyingVector2);

  @override
  double get x =>
      (super.noSuchMethod(
            Invocation.getter(#x),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get y =>
      (super.noSuchMethod(
            Invocation.getter(#y),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get angle =>
      (super.noSuchMethod(
            Invocation.getter(#angle),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i6.NotifyingVector2 get scale =>
      (super.noSuchMethod(
            Invocation.getter(#scale),
            returnValue: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#scale),
            ),
            returnValueForMissingStub: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#scale),
            ),
          )
          as _i6.NotifyingVector2);

  @override
  _i2.Anchor get anchor =>
      (super.noSuchMethod(
            Invocation.getter(#anchor),
            returnValue: _FakeAnchor_27(this, Invocation.getter(#anchor)),
            returnValueForMissingStub: _FakeAnchor_27(
              this,
              Invocation.getter(#anchor),
            ),
          )
          as _i2.Anchor);

  @override
  _i6.NotifyingVector2 get size =>
      (super.noSuchMethod(
            Invocation.getter(#size),
            returnValue: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#size),
            ),
            returnValueForMissingStub: _FakeNotifyingVector2_26(
              this,
              Invocation.getter(#size),
            ),
          )
          as _i6.NotifyingVector2);

  @override
  double get width =>
      (super.noSuchMethod(
            Invocation.getter(#width),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get height =>
      (super.noSuchMethod(
            Invocation.getter(#height),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i6.Vector2 get scaledSize =>
      (super.noSuchMethod(
            Invocation.getter(#scaledSize),
            returnValue: _FakeVector2_6(this, Invocation.getter(#scaledSize)),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#scaledSize),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get absoluteScaledSize =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteScaledSize),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteScaledSize),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteScaledSize),
            ),
          )
          as _i6.Vector2);

  @override
  double get absoluteAngle =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteAngle),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  double get absoluteAngleWithoutReflection =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteAngleWithoutReflection),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  _i6.Vector2 get absoluteScale =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteScale),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteScale),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteScale),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get topLeftPosition =>
      (super.noSuchMethod(
            Invocation.getter(#topLeftPosition),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#topLeftPosition),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#topLeftPosition),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get center =>
      (super.noSuchMethod(
            Invocation.getter(#center),
            returnValue: _FakeVector2_6(this, Invocation.getter(#center)),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#center),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get absolutePosition =>
      (super.noSuchMethod(
            Invocation.getter(#absolutePosition),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#absolutePosition),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#absolutePosition),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get absoluteTopLeftPosition =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteTopLeftPosition),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteTopLeftPosition),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteTopLeftPosition),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 get absoluteCenter =>
      (super.noSuchMethod(
            Invocation.getter(#absoluteCenter),
            returnValue: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteCenter),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.getter(#absoluteCenter),
            ),
          )
          as _i6.Vector2);

  @override
  bool get isFlippedHorizontally =>
      (super.noSuchMethod(
            Invocation.getter(#isFlippedHorizontally),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isFlippedVertically =>
      (super.noSuchMethod(
            Invocation.getter(#isFlippedVertically),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set nativeAngle(double? value) => super.noSuchMethod(
    Invocation.setter(#nativeAngle, value),
    returnValueForMissingStub: null,
  );

  @override
  set decorator(_i18.Decorator? value) => super.noSuchMethod(
    Invocation.setter(#decorator, value),
    returnValueForMissingStub: null,
  );

  @override
  set position(_i6.Vector2? position) => super.noSuchMethod(
    Invocation.setter(#position, position),
    returnValueForMissingStub: null,
  );

  @override
  set x(double? x) => super.noSuchMethod(
    Invocation.setter(#x, x),
    returnValueForMissingStub: null,
  );

  @override
  set y(double? y) => super.noSuchMethod(
    Invocation.setter(#y, y),
    returnValueForMissingStub: null,
  );

  @override
  set angle(double? a) => super.noSuchMethod(
    Invocation.setter(#angle, a),
    returnValueForMissingStub: null,
  );

  @override
  set scale(_i6.Vector2? scale) => super.noSuchMethod(
    Invocation.setter(#scale, scale),
    returnValueForMissingStub: null,
  );

  @override
  set anchor(_i2.Anchor? anchor) => super.noSuchMethod(
    Invocation.setter(#anchor, anchor),
    returnValueForMissingStub: null,
  );

  @override
  set size(_i6.Vector2? size) => super.noSuchMethod(
    Invocation.setter(#size, size),
    returnValueForMissingStub: null,
  );

  @override
  set width(double? w) => super.noSuchMethod(
    Invocation.setter(#width, w),
    returnValueForMissingStub: null,
  );

  @override
  set height(double? h) => super.noSuchMethod(
    Invocation.setter(#height, h),
    returnValueForMissingStub: null,
  );

  @override
  set topLeftPosition(_i6.Vector2? point) => super.noSuchMethod(
    Invocation.setter(#topLeftPosition, point),
    returnValueForMissingStub: null,
  );

  @override
  set center(_i6.Vector2? point) => super.noSuchMethod(
    Invocation.setter(#center, point),
    returnValueForMissingStub: null,
  );

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoaded =>
      (super.noSuchMethod(
            Invocation.getter(#isLoaded),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMounting =>
      (super.noSuchMethod(
            Invocation.getter(#isMounting),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isMounted =>
      (super.noSuchMethod(
            Invocation.getter(#isMounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRemoving =>
      (super.noSuchMethod(
            Invocation.getter(#isRemoving),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isRemoved =>
      (super.noSuchMethod(
            Invocation.getter(#isRemoved),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i20.Future<void> get loaded =>
      (super.noSuchMethod(
            Invocation.getter(#loaded),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i20.Future<void> get removed =>
      (super.noSuchMethod(
            Invocation.getter(#removed),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  _i8.ReadOnlyOrderedSet<_i2.Component> get children =>
      (super.noSuchMethod(
            Invocation.getter(#children),
            returnValue: _FakeReadOnlyOrderedSet_8<_i2.Component>(
              this,
              Invocation.getter(#children),
            ),
            returnValueForMissingStub: _FakeReadOnlyOrderedSet_8<_i2.Component>(
              this,
              Invocation.getter(#children),
            ),
          )
          as _i8.ReadOnlyOrderedSet<_i2.Component>);

  @override
  bool get hasChildren =>
      (super.noSuchMethod(
            Invocation.getter(#hasChildren),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get priority =>
      (super.noSuchMethod(
            Invocation.getter(#priority),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  bool get debugMode =>
      (super.noSuchMethod(
            Invocation.getter(#debugMode),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Color get debugColor =>
      (super.noSuchMethod(
            Invocation.getter(#debugColor),
            returnValue: _FakeColor_9(this, Invocation.getter(#debugColor)),
            returnValueForMissingStub: _FakeColor_9(
              this,
              Invocation.getter(#debugColor),
            ),
          )
          as _i9.Color);

  @override
  _i9.Paint get debugPaint =>
      (super.noSuchMethod(
            Invocation.getter(#debugPaint),
            returnValue: _i21.dummyValue<_i9.Paint>(
              this,
              Invocation.getter(#debugPaint),
            ),
            returnValueForMissingStub: _i21.dummyValue<_i9.Paint>(
              this,
              Invocation.getter(#debugPaint),
            ),
          )
          as _i9.Paint);

  @override
  _i6.TextPaint get debugTextPaint =>
      (super.noSuchMethod(
            Invocation.getter(#debugTextPaint),
            returnValue: _FakeTextPaint_10(
              this,
              Invocation.getter(#debugTextPaint),
            ),
            returnValueForMissingStub: _FakeTextPaint_10(
              this,
              Invocation.getter(#debugTextPaint),
            ),
          )
          as _i6.TextPaint);

  @override
  set parent(_i2.Component? newParent) => super.noSuchMethod(
    Invocation.setter(#parent, newParent),
    returnValueForMissingStub: null,
  );

  @override
  set priority(int? newPriority) => super.noSuchMethod(
    Invocation.setter(#priority, newPriority),
    returnValueForMissingStub: null,
  );

  @override
  set debugMode(bool? value) => super.noSuchMethod(
    Invocation.setter(#debugMode, value),
    returnValueForMissingStub: null,
  );

  @override
  set debugCoordinatesPrecision(int? value) => super.noSuchMethod(
    Invocation.setter(#debugCoordinatesPrecision, value),
    returnValueForMissingStub: null,
  );

  @override
  set debugColor(_i9.Color? value) => super.noSuchMethod(
    Invocation.setter(#debugColor, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.MyPixelGame get game =>
      (super.noSuchMethod(
            Invocation.getter(#game),
            returnValue: _FakeMyPixelGame_28(this, Invocation.getter(#game)),
            returnValueForMissingStub: _FakeMyPixelGame_28(
              this,
              Invocation.getter(#game),
            ),
          )
          as _i3.MyPixelGame);

  @override
  _i3.MyPixelGame get gameRef =>
      (super.noSuchMethod(
            Invocation.getter(#gameRef),
            returnValue: _FakeMyPixelGame_28(this, Invocation.getter(#gameRef)),
            returnValueForMissingStub: _FakeMyPixelGame_28(
              this,
              Invocation.getter(#gameRef),
            ),
          )
          as _i3.MyPixelGame);

  @override
  set game(_i3.MyPixelGame? value) => super.noSuchMethod(
    Invocation.setter(#game, value),
    returnValueForMissingStub: null,
  );

  @override
  _i20.Future<void> onLoad() =>
      (super.noSuchMethod(
            Invocation.method(#onLoad, []),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  void applyParalysis(double? duration) => super.noSuchMethod(
    Invocation.method(#applyParalysis, [duration]),
    returnValueForMissingStub: null,
  );

  @override
  void jump() => super.noSuchMethod(
    Invocation.method(#jump, []),
    returnValueForMissingStub: null,
  );

  @override
  void dash() => super.noSuchMethod(
    Invocation.method(#dash, []),
    returnValueForMissingStub: null,
  );

  @override
  void basicAttack() => super.noSuchMethod(
    Invocation.method(#basicAttack, []),
    returnValueForMissingStub: null,
  );

  @override
  void specialAttack() => super.noSuchMethod(
    Invocation.method(#specialAttack, []),
    returnValueForMissingStub: null,
  );

  @override
  void startBlocking() => super.noSuchMethod(
    Invocation.method(#startBlocking, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopBlocking() => super.noSuchMethod(
    Invocation.method(#stopBlocking, []),
    returnValueForMissingStub: null,
  );

  @override
  void receiveAttack(double? bossDamage) => super.noSuchMethod(
    Invocation.method(#receiveAttack, [bossDamage]),
    returnValueForMissingStub: null,
  );

  @override
  void update(double? dt) => super.noSuchMethod(
    Invocation.method(#update, [dt]),
    returnValueForMissingStub: null,
  );

  @override
  void render(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#render, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  double distance(_i2.PositionComponent? other) =>
      (super.noSuchMethod(
            Invocation.method(#distance, [other]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  bool containsLocalPoint(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#containsLocalPoint, [point]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool containsPoint(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#containsPoint, [point]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Vector2 parentToLocal(_i6.Vector2? point, {_i6.Vector2? output}) =>
      (super.noSuchMethod(
            Invocation.method(#parentToLocal, [point], {#output: output}),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#parentToLocal, [point], {#output: output}),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#parentToLocal, [point], {#output: output}),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 localToParent(_i6.Vector2? point, {_i6.Vector2? output}) =>
      (super.noSuchMethod(
            Invocation.method(#localToParent, [point], {#output: output}),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#localToParent, [point], {#output: output}),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#localToParent, [point], {#output: output}),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 positionOf(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#positionOf, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#positionOf, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#positionOf, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 positionOfAnchor(_i2.Anchor? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#positionOfAnchor, [anchor]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#positionOfAnchor, [anchor]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#positionOfAnchor, [anchor]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 absolutePositionOf(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#absolutePositionOf, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#absolutePositionOf, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#absolutePositionOf, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 absolutePositionOfAnchor(_i2.Anchor? anchor) =>
      (super.noSuchMethod(
            Invocation.method(#absolutePositionOfAnchor, [anchor]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#absolutePositionOfAnchor, [anchor]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#absolutePositionOfAnchor, [anchor]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 toLocal(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#toLocal, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#toLocal, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#toLocal, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  _i6.Vector2 absoluteToLocal(_i6.Vector2? point) =>
      (super.noSuchMethod(
            Invocation.method(#absoluteToLocal, [point]),
            returnValue: _FakeVector2_6(
              this,
              Invocation.method(#absoluteToLocal, [point]),
            ),
            returnValueForMissingStub: _FakeVector2_6(
              this,
              Invocation.method(#absoluteToLocal, [point]),
            ),
          )
          as _i6.Vector2);

  @override
  double angleTo(_i6.Vector2? target) =>
      (super.noSuchMethod(
            Invocation.method(#angleTo, [target]),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  void lookAt(_i6.Vector2? target) => super.noSuchMethod(
    Invocation.method(#lookAt, [target]),
    returnValueForMissingStub: null,
  );

  @override
  void flipHorizontally() => super.noSuchMethod(
    Invocation.method(#flipHorizontally, []),
    returnValueForMissingStub: null,
  );

  @override
  void flipVertically() => super.noSuchMethod(
    Invocation.method(#flipVertically, []),
    returnValueForMissingStub: null,
  );

  @override
  void flipHorizontallyAroundCenter() => super.noSuchMethod(
    Invocation.method(#flipHorizontallyAroundCenter, []),
    returnValueForMissingStub: null,
  );

  @override
  void flipVerticallyAroundCenter() => super.noSuchMethod(
    Invocation.method(#flipVerticallyAroundCenter, []),
    returnValueForMissingStub: null,
  );

  @override
  void renderDebugMode(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#renderDebugMode, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  void renderTree(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#renderTree, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  void renderTreeWithoutDecorator(_i9.Canvas? canvas) => super.noSuchMethod(
    Invocation.method(#renderTreeWithoutDecorator, [canvas]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Rect toRect() =>
      (super.noSuchMethod(
            Invocation.method(#toRect, []),
            returnValue: _FakeRect_29(this, Invocation.method(#toRect, [])),
            returnValueForMissingStub: _FakeRect_29(
              this,
              Invocation.method(#toRect, []),
            ),
          )
          as _i9.Rect);

  @override
  _i9.Rect toAbsoluteRect() =>
      (super.noSuchMethod(
            Invocation.method(#toAbsoluteRect, []),
            returnValue: _FakeRect_29(
              this,
              Invocation.method(#toAbsoluteRect, []),
            ),
            returnValueForMissingStub: _FakeRect_29(
              this,
              Invocation.method(#toAbsoluteRect, []),
            ),
          )
          as _i9.Rect);

  @override
  void setByRect(_i9.Rect? rect) => super.noSuchMethod(
    Invocation.method(#setByRect, [rect]),
    returnValueForMissingStub: null,
  );

  @override
  void rebalanceChildren() => super.noSuchMethod(
    Invocation.method(#rebalanceChildren, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.OrderedSet<_i2.Component> createComponentSet() =>
      (super.noSuchMethod(
            Invocation.method(#createComponentSet, []),
            returnValue: _FakeOrderedSet_19<_i2.Component>(
              this,
              Invocation.method(#createComponentSet, []),
            ),
            returnValueForMissingStub: _FakeOrderedSet_19<_i2.Component>(
              this,
              Invocation.method(#createComponentSet, []),
            ),
          )
          as _i16.OrderedSet<_i2.Component>);

  @override
  T? findParent<T extends _i2.Component>({bool? includeSelf = false}) =>
      (super.noSuchMethod(
            Invocation.method(#findParent, [], {#includeSelf: includeSelf}),
            returnValueForMissingStub: null,
          )
          as T?);

  @override
  Iterable<_i2.Component> ancestors({bool? includeSelf = false}) =>
      (super.noSuchMethod(
            Invocation.method(#ancestors, [], {#includeSelf: includeSelf}),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  Iterable<_i2.Component> descendants({
    bool? includeSelf = false,
    bool? reversed = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#descendants, [], {
              #includeSelf: includeSelf,
              #reversed: reversed,
            }),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  bool propagateToChildren<T extends _i2.Component>(
    bool Function(T)? handler, {
    bool? includeSelf = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #propagateToChildren,
              [handler],
              {#includeSelf: includeSelf},
            ),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool contains(_i2.Component? c) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [c]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onGameResize(_i6.Vector2? size) => super.noSuchMethod(
    Invocation.method(#onGameResize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  void onMount() => super.noSuchMethod(
    Invocation.method(#onMount, []),
    returnValueForMissingStub: null,
  );

  @override
  void onRemove() => super.noSuchMethod(
    Invocation.method(#onRemove, []),
    returnValueForMissingStub: null,
  );

  @override
  void onParentResize(_i6.Vector2? maxSize) => super.noSuchMethod(
    Invocation.method(#onParentResize, [maxSize]),
    returnValueForMissingStub: null,
  );

  @override
  void updateTree(double? dt) => super.noSuchMethod(
    Invocation.method(#updateTree, [dt]),
    returnValueForMissingStub: null,
  );

  @override
  void onChildrenChanged(_i2.Component? child, _i2.ChildrenChangeType? type) =>
      super.noSuchMethod(
        Invocation.method(#onChildrenChanged, [child, type]),
        returnValueForMissingStub: null,
      );

  @override
  _i20.FutureOr<void> add(_i2.Component? component) =>
      (super.noSuchMethod(
            Invocation.method(#add, [component]),
            returnValueForMissingStub: null,
          )
          as _i20.FutureOr<void>);

  @override
  _i20.FutureOr<void> addToParent(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#addToParent, [parent]),
            returnValueForMissingStub: null,
          )
          as _i20.FutureOr<void>);

  @override
  _i20.Future<void> addAll(Iterable<_i2.Component>? components) =>
      (super.noSuchMethod(
            Invocation.method(#addAll, [components]),
            returnValue: _i20.Future<void>.value(),
            returnValueForMissingStub: _i20.Future<void>.value(),
          )
          as _i20.Future<void>);

  @override
  void remove(_i2.Component? component) => super.noSuchMethod(
    Invocation.method(#remove, [component]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFromParent() => super.noSuchMethod(
    Invocation.method(#removeFromParent, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeAll(Iterable<_i2.Component>? components) => super.noSuchMethod(
    Invocation.method(#removeAll, [components]),
    returnValueForMissingStub: null,
  );

  @override
  void removeWhere(bool Function(_i2.Component)? test) => super.noSuchMethod(
    Invocation.method(#removeWhere, [test]),
    returnValueForMissingStub: null,
  );

  @override
  Iterable<_i2.Component> componentsAtPoint(
    _i6.Vector2? point, [
    List<_i6.Vector2>? nestedPoints,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#componentsAtPoint, [point, nestedPoints]),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  Iterable<_i2.Component> componentsAtLocation<T>(
    T? locationContext,
    List<T>? nestedContexts,
    T? Function(_i2.CoordinateTransform, T)? transformContext,
    bool Function(_i2.Component, T)? checkContains,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#componentsAtLocation, [
              locationContext,
              nestedContexts,
              transformContext,
              checkContains,
            ]),
            returnValue: <_i2.Component>[],
            returnValueForMissingStub: <_i2.Component>[],
          )
          as Iterable<_i2.Component>);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventAdd(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventAdd, [parent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventRemove(_i2.Component? parent) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventRemove, [parent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  _i19.LifecycleEventStatus handleLifecycleEventMove(
    _i2.Component? newParent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleLifecycleEventMove, [newParent]),
            returnValue: _i19.LifecycleEventStatus.skip,
            returnValueForMissingStub: _i19.LifecycleEventStatus.skip,
          )
          as _i19.LifecycleEventStatus);

  @override
  void handleResize(_i6.Vector2? size) => super.noSuchMethod(
    Invocation.method(#handleResize, [size]),
    returnValueForMissingStub: null,
  );

  @override
  void setLoaded() => super.noSuchMethod(
    Invocation.method(#setLoaded, []),
    returnValueForMissingStub: null,
  );

  @override
  void setMounted() => super.noSuchMethod(
    Invocation.method(#setMounted, []),
    returnValueForMissingStub: null,
  );

  @override
  void setRemoved() => super.noSuchMethod(
    Invocation.method(#setRemoved, []),
    returnValueForMissingStub: null,
  );
}
